<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\EscalationService;

class RunTestEscalation extends Command
{
    protected $signature = 'pearlie:test-escalation {session=manual-test}';
    protected $description = 'Create a test escalation and run notification flow';

    public function handle(EscalationService $escalationService)
    {
        $session = $this->argument('session');
        $this->info('Creating test escalation for session: ' . $session);

        try {
            $esc = $escalationService->createEscalation($session, 'This is a test escalation generated by pearlie:test-escalation', 'AI replied: I am not sure');
            $this->info('Escalation created with ID: ' . $esc->id);
            return 0;
        } catch (\Throwable $e) {
            $this->error('Failed to create test escalation: ' . $e->getMessage());
            return 1;
        }
    }
}
