<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\EscalationService;

class SendTestEscalation extends Command
{
    protected $signature = 'pearlie:send-test-escalation {session?}';
    protected $description = 'Create a test escalation and send notifications (email/SMS/WhatsApp)';

    public function handle(EscalationService $svc)
    {
        $session = $this->argument('session') ?: 'manual-test-' . time();

        $esc = $svc->createEscalation($session, 'This is a test escalation generated by artisan command', 'Test AI response');

        $this->info('Created escalation id: ' . $esc->id);
        $this->info('Notifications dispatched (email queued, SMS/WhatsApp attempted).');

        return 0;
    }
}
